modLoader = "javafml" #mandatory
loaderVersion = "[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All rights reserved"
[[mods]] #mandatory
modId = "tutorialmod" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Tutorial Mod" #mandatory
description = "Hello There!"
[[dependencies.tutorialmod]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[32,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.tutorialmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.1]"
ordering = "NONE"
side = "BOTH"
